# Build and publish documentation.

name: Docs

on:
  push:
    branches: [main]
    paths:
      - docs/**
      - ts2vg/**
      - README.*
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build and install ts2vg and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r docs_requirements.txt
          python -m pip install --editable .

      - name: Build documentation
        working-directory: docs
        run: |
          make html

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/build/html
