# Build and publish documentation.

name: Docs

on:
  push:
    branches: [main]
    paths:
      - docs/**
      - ts2vg/**

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Build and install ts2vg and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r doc_requirements.txt

      - name: Build documentation
        working-directory: docs
        run: |
          make html

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/build/html
